spring:
  main:
    banner-mode: off

server:
  port: 8080

instance:
  key: gateway
  id: 1

grpc:
  client:
    user-service:
      address: localhost
      port: 9091
    authentication-service:
      address: localhost
      port: 9092
    role-service:
      address: localhost
      port: 9093
